#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-stretch-slim AS base

WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:2.2-stretch AS build
WORKDIR /src
COPY ["NetCoreTest.csproj", ""]
RUN dotnet restore "./NetCoreTest.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "NetCoreTest.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "NetCoreTest.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

COPY domain.pfx .

ENV ASPNETCORE_ENVIRONMENT=Production
ENV ASPNETCORE_HTTPS_PORT="5001"
ENV ASPNETCORE_Kestrel__Certificates__Default__Password="137600"
ENV ASPNETCORE_Kestrel__Certificates__Default__Path="./domain.pfx"
#ENV ASPNETCORE_URLS=http://*:8080;https://*:443
ENV ASPNETCORE_URLS="https://+;http://+"

ENTRYPOINT ["dotnet", "NetCoreTest.dll"]